
/*
 * SplashScreenFrame.java
 *
 * Created on Jun 19, 2010, 5:17:05 PM
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * Displays the splash scren at the start of the progam
 * @author Anurag Sharma
 */
public class SplashScreenFrame extends javax.swing.JFrame {

    private LibrarySelectionPanel librarySelectionPanel;
    private DatasetParametersPanel datasetPanel;

    /** Creates new form SplashScreenFrame */
    public SplashScreenFrame() {
        initComponents();
        customInit();
    }

    /**
     * performs initialization of location of the splash screen
     */
    void customInit() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getWidth(), h = this.getHeight();
        int x = (d.width - w) / 2, y = (d.height - h) / 2;
        this.setLocation(x, y);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spashScreenImage.gif"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jProgressBar1.setForeground(new java.awt.Color(0, 204, 0));
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setName("jProgressBar1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * tests the class independently
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SplashScreenFrame().setVisible(true);
//            }
//        });

        SplashScreenFrame splash = new SplashScreenFrame();
        splash.doSomething();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private void doSomething() {
        this.setVisible(true);
        new Thread() {
            @Override
            public void run() {
                System.out.println("showing splash screen");
                //do initial processing here.
                librarySelectionPanel = new LibrarySelectionPanel();
                datasetPanel = new DatasetParametersPanel(librarySelectionPanel);

                BaseFrame baseFrame = new BaseFrame(librarySelectionPanel, datasetPanel);
                int w = baseFrame.getWidth(), h = baseFrame.getHeight();
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (d.width - w) / 2, y = (d.height - h) / 2;
                baseFrame.setLocation(x, y);
                baseFrame.setVisible(true);

                System.out.println("hiding splash screen");
                SplashScreenFrame.this.setVisible(false);
                SplashScreenFrame.this.dispose();
            }
        }.start();
    }
}
