package gui;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * InformationPanel.java
 *
 * Created on 6 Jun, 2010, 1:02:02 AM
 */
/**
 * This is responsible for displaying the information which user has selected in various screens
 * @author Anurag Sharma
 */
public class InformationPanel extends javax.swing.JPanel {

    private CELSelectionPanel celPanel;
    private LibrarySelectionPanel screen2Panel;

    /** Creates new form InformationPanel */
    public InformationPanel(CELSelectionPanel cp, LibrarySelectionPanel sp) {
        initComponents();

        celPanel = cp;
        screen2Panel = sp;

//        fillInformation();
    }

    /**
     * Retrieves information filled by the user and populates in various fields
     * @return the exit status (0-success and 1-failure)
     */
    int fillInformation() {
        ArrayList<File> celFiles = celPanel.getCELFileList();
//        ArrayList<File> libFiles = screen2Panel.getLibraryFiles();
        ArrayList<String> algos = screen2Panel.getAlgorithms();

        String str = "";

        for (File file : celFiles) {
            str += file.getName() + ", ";
        }

        if (str.length() > 28) {
            str = str.substring(0, 25) + "...";
        }
        String pgfFile = "", clfFile = "", bgpFile = "", qccFile = "", psFile = "";

        try {
            if (screen2Panel.isPgfSelected()) {
                pgfFile = screen2Panel.getPgfLibraryFile().getName();
            }

            if (screen2Panel.isClfSelected()) {
                clfFile = screen2Panel.getClfLibraryFile().getName();
            }

            if (screen2Panel.isBgpSelected()) {
                bgpFile = screen2Panel.getBgpLibraryFile().getName();
            }

            if (screen2Panel.isQccSelected()) {
                qccFile = screen2Panel.getQccLibraryFile().getName();
            }

            if (screen2Panel.isPsSelected()) {
                psFile = screen2Panel.getPsLibraryFile().getName();
            }

            jLabel8.setText(str);
            jLabel9.setText(pgfFile);
            jLabel10.setText(clfFile);
            jLabel11.setText(bgpFile);
            jLabel12.setText(qccFile);
            jLabel13.setText(psFile);

            str = "";
            if (algos.size() > 0) {
                str += algos.get(0);
            }
            if (algos.size() > 1) {
                str += ", " + algos.get(1);
            }

            jLabel14.setText(str);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Some required fields left empty in previous screen");
            System.out.println("Error::");
//            e.printStackTrace();
            return 1;
        }
        return 0;
    }

    /** This method is called from within the con structor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 190, 250));

        jLabel1.setText("PGF file:");

        jLabel2.setText("CLF file:");

        jLabel3.setText("BGP file:");

        jLabel4.setText("QCC file:");

        jLabel5.setText("PS file:");

        jLabel6.setText("Algorithms :");

        jLabel7.setText("CEL files:");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
