package gui;

import data.FileLocator;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/*
 * IntroductionPanel.java
 *
 * Created on 5 Jun, 2010, 11:30:41 PM
 */
/**
 * This class is responsible for displaying the GPL license
 * @author Anurag Sharma
 */
public class IntroductionPanel extends javax.swing.JPanel {

    /** Creates new form IntroductionPanel */
    public IntroductionPanel() {
        initComponents();
        customInit();
    }

    /**
     * Loads the GPL text from file and displays it
     */
    void customInit() {
        try {
            Scanner sc = new Scanner(new File(FileLocator.resDirLocation + "/gpl-2.0.txt"));
            String str = "";
            while (sc.hasNextLine()) {
                str += sc.nextLine() + "\n";
            }
//            System.out.println("-----------------Licence--------------");
//            System.out.println(str);
            jTextArea1.setText(str);
            jTextArea1.setCaretPosition(0);
        } catch (FileNotFoundException ex) {
            jTextArea1.setText("GNU Licence is missing");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(200, 190, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/affymetrix_logo.gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18));
        jLabel2.setText("Affymetrix Power Tools");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
